.TH GINA 1 "02 February 2009" "1.0.0" "User Commands"

.SH NAME
Gina \- Virtual sticky notes

.SH SYNOPSIS
\fBgina\fR

.SH DESCRIPTION
\fBGina\fR is a simple program that provides virtual sticky notes for your
desktop. It\'s handy for jotting down quick notes or holding copied text that
you plan to past elsewhere later.
.PP
Notes can be saved as plain text for later viewing/editing with \fBGina\fR \-\-
or any other text editor, for that matter.
.PP
\fBGina\fR is designed to be "keyboard friendly", that is, every possible action
is bound to a specific keystroke.
.PP
The name \fBGina\fR is a recursive acronym standing for "Gina isn\'t Nina
anymore"; the name is called for, because \fBGina\fR is a 90% compatible Vala/GTK+
clone of Nina version 0.6.6.
.PP
Nina, now known as Rhinote, is a Python/Tk script developed by Marv Boyes.

.SH KEY BINDINGS
.TP
\fBCtrl+N\fB
Create new (blank) note.
.TP
\fBCtrl+O\fR
Load note from file.
.TP
\fBCtrl+S\fR
Save current note.
.TP
\fBCtrl+C\fR
Copy highlighted text.
.TP
\fBCtrl+X\fR
Cut highlighted text.
.TP
\fBCtrl+V\fR
Paste text from clipboard.
.TP
\fBCtrl+M\fR
Toggle menubar.
.TP
\fBCtrl+D\fR
Toggle window decorations (not guaranteed to work with every window manager).
.TP
\fBCtrl+H\fR
Display all available key bindings.

.SH AUTHOR
This manual page was written by Andrea Bolognani <eof@kiyuko.org>
